data_name: scannet
rawdata_dir: /scratches/flyer_3/fx221/dataset/scannet_eval_release/data
feature_dump_dir: /scratches/flyer_2/fx221/dataset/test_imp/scannet
dataset_dump_dir: /scratches/flyer_2/fx221/dataset/test_imp/scannet

extractor:
  name: root #root or sp
  num_kpt: 2000
  resize: [480,640]
  overwrite: False
  extract: True
  num_process: 4
  det_th: 0.00001