data_name: scannet
rawdata_dir: /mnt/nas/share-all/kecen/data/scannet_eval_release/data
feature_dump_dir: /mnt/nas/share-all/kecen/data/scannet_eval_release/feature
dataset_dump_dir: /mnt/nas/share-all/kecen/data/scannet_eval_release/dataset
extractor:
  name: sp #root or sp
  num_kpt: 1000
  resize: [ 480,640 ]
  overwrite: False
  extract: True
  num_process: 4
  det_th: 0.005