data_name: scannet
rawdata_dir: /mnt/nas/share-all/kecen/data/scannet_eval_release/data
feature_dump_dir: /mnt/nas/share-all/kecen/data/scannet_eval_release/feature
dataset_dump_dir: //mnt/nas/share-all/kecen/data/scannet_eval_release/dataset

extractor:
  name: root #root or sp
  num_kpt: 2000
  resize: [480,640]
  overwrite: False
  extract: True
  num_process: 4
  det_th: 0.00001