data_name: yfcc
rawdata_dir: /scratches/flyer_3/fx221/dataset/YFCC/data
feature_dump_dir: /scratches/flyer_2/fx221/dataset/test_imp/yfcc
dataset_dump_dir: /scratches/flyer_2/fx221/dataset/test_imp/yfcc
data_split: [ 'test' ]
data_seq: [ 'buckingham_palace', 'notre_dame_front_facade', 'reichstag', 'sacre_coeur' ]

extractor:
  name: sp #root or sp
  num_kpt: 2000
  resize: [ 1600 ]
  overwrite: False
  extract: True
  num_process: 4
  det_th: 0.005