reader:
  name: standard
  rawdata_dir: /scratches/flyer_3/fx221/dataset/FMBench/data
  dataset_dir: /scratches/flyer_3/fx221/dataset/FMBench/eval/fmbench_root_4000.hdf5
  num_kpt: 4000

matcher:
  name: GM
  model_dir: ../weights/gm/sp
  net_channels: 128
  layer_num: 9
  head: 4
  use_score_encoding: True
  sink_iter: [ 20 ]
  p_th: 0.2

evaluator:
  name: FM
  seq: [ 'CPC','KITTI','TUM','Tanks_and_Temples' ]
  num_pair: 4000
  inlier_th: 0.003
  sgd_inlier_th: 0.05
