reader:
  name: standard
  rawdata_dir: /scratches/flyer_3/fx221/dataset/YFCC/data
  dataset_dir: /scratches/flyer_3/fx221/dataset/YFCC/eval/yfcc_root_2000.hdf5
  num_kpt: 2000
  
matcher:
  name: GM
  model_dir: ../weights/gm/sp
  net_channels: 256
  layer_num: 9
  head: 4
  use_score_encoding: True
  sink_iter: [20]
  p_th: 0.2

evaluator:
  name: AUC
  rescale: 1600
  num_pair: 4000
  inlier_th: 0.005

